MyPortfolioProject/Controllers/InternshipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPortfolioProject.Models;

namespace MyPortfolioProject.Controllers
{
    public class InternshipController : Controller
    {
        // GET: Internship
        DbMyPortfolioEntities context = new DbMyPortfolioEntities();
        public ActionResult InternshipList()
        {
            var values = context.Internship.ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult CreateInternship()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateInternship(Internship internship)
        {
            if (ModelState.IsValid)
            {
                context.Internship.Add(internship);
                context.SaveChanges();
                return RedirectToAction(nameof(InternshipList));
            }
            return View(internship);
        }
        public ActionResult DeleteInternship(int id)
        {
            var value = context.Internship.Find(id);
            context.Internship.Remove(value);
            context.SaveChanges();
            return RedirectToAction(nameof(InternshipList));
        }
        [HttpGet]
        public ActionResult UpdateInternship(int id)
        {
            var value = context.Internship.Find(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult UpdateInternship(Internship internship)
        {
            var value = context.Internship.Find(internship.InternshipID);
            value.CompanyName = internship.CompanyName;
            value.StartDate = internship.StartDate;
            value.EndDate = internship.EndDate;
            value.Position = internship.Position;
            value.Description = internship.Description;
            value.ReferenceName = internship.ReferenceName;
            value.ReferenceEmail = internship.ReferenceEmail;
            context.SaveChanges();
            return RedirectToAction(nameof(InternshipList));
        }
    }
}

MyPortfolioProject/Views/Internship/CreateInternship.cshtml
@{
    ViewBag.Title = "CreateInternship";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Yeni Staj Ekleme Sayfası</h2>

<form method="post">
    <label>Şirket Adı</label>
    <input type="text" name="CompanyName" class="form-control" />
    @Html.ValidationMessage("CompanyName", "", new { @class = "text-danger" })
    <br />
    <label>Başlangıç Tarihi</label>
    <input type="text" name="StartDate" class="form-control" />
    @Html.ValidationMessage("StartDate", "", new { @class = "text-danger" })
    <br />
    <label>Bitiş Tarihi</label>
    <input type="text" name="EndDate" class="form-control" />
    @Html.ValidationMessage("EndDate", "", new { @class = "text-danger" })
    <br />
    <label>Pozisyon</label>
    <input type="text" name="Position" class="form-control" />
    @Html.ValidationMessage("Position", "", new { @class = "text-danger" })
    <br />
    <label>Açıklama</label>
    <input type="text" name="Description" class="form-control" />
    @Html.ValidationMessage("Description", "", new { @class = "text-danger" })
    <br />
    <label>Referans Adı</label>
    <input type="text" name="ReferenceName" class="form-control" />
    @Html.ValidationMessage("ReferenceName", "", new { @class = "text-danger" })
    <br />
    <label>Referans E-Mail</label>
    <input type="email" name="ReferenceEmail" class="form-control"/>
    @Html.ValidationMessage("ReferenceEmail", "", new { @class = "text-danger" })
    <br />
    <button class="btn btn-outline-info">Yeteneği Ekle</button>
</form>

MyPortfolioProject/Views/Internship/InternshipList.cshtml
@model List<MyPortfolioProject.Models.Internship>
@{
    ViewBag.Title = "InternshipList";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Staj Listesi ve İşlemleri</h2>

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Şirket Adı</th>
        <th>Başlangıç Tarihi</th>
        <th>Bitiş Tarihi</th>
        <th>Pozisyon</th>
        <th>Açıklama</th>
        <th>Referans Adı</th>
        <th>Referans E-Maili</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.InternshipID</td>
            <td>@item.CompanyName</td>
            <td>@item.StartDate</td>
            <td>@item.EndDate</td>
            <td>@item.Position</td>
            <td>@item.Description</td>
            <td>@item.ReferenceName</td>
            <td>@item.ReferenceEmail</td>
            <td><a href="/Internship/DeleteInternship/@item.InternshipID/" class="btn btn-outline-danger">Sil</a></td>
            <td><a href="/Internship/UpdateInternship/@item.InternshipID/" class="btn btn-outline-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Internship/CreateInternship/" class="btn btn-outline-info">Staj Ekle</a>

MyPortfolioProject/Views/Internship/UpdateInternship.cshtml
@model MyPortfolioProject.Models.Internship
@{
    ViewBag.Title = "UpdateInternship";
    Layout = "~/Views/Admin/Index.cshtml";
}

@using (Html.BeginForm("UpdateInternship", "Internship", FormMethod.Post))
{
    @Html.HiddenFor(k => k.InternshipID)
<div class="form-group">
    <label>Şirket Adı</label>
    @Html.TextBoxFor(k => k.CompanyName, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("CompanyName", "", new { @class = "text-danger" })
</div>
<div class="form-group">
    <label>Başlangıç Tarihi</label>
    @Html.TextBoxFor(k => k.StartDate, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("StartDate", "", new { @class = "text-danger" })
</div>
<div class="form-group">
    <label>Bitiş Tarihi</label>
    @Html.TextBoxFor(k => k.EndDate, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("EndDate", "", new { @class = "text-danger" })
</div>
<div class="form-group">
    <label>Pozisyon</label>
    @Html.TextBoxFor(k => k.Position, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("Position", "", new { @class = "text-danger" })
</div>
<div class="form-group">
    <label>Açıklama</label>
    @Html.TextBoxFor(k => k.Description, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("Description", "", new { @class = "text-danger" })
</div>
<div class="form-group">
    <label>Referans Adı</label>
    @Html.TextBoxFor(k => k.ReferenceName, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("ReferenceName", "", new { @class = "text-danger" })
</div>
<div class="form-group">
    <label>Referans E-Maili</label>
    @Html.TextBoxFor(k => k.ReferenceEmail, new { @class = "form-control", required = "required" })
    @Html.ValidationMessage("ReferenceEmail", "", new { @class = "text-danger" })
</div>
    <div style="margin-top:15px">
        <button class="btn btn btn-outline-info">Güncelle</button>
    </div>
}