MyPortfolioProject/Controllers/SkillController.cs
using MyPortfolioProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace MyPortfolioProject.Controllers
{
    public class SkillController : Controller
    {
        DbMyPortfolioEntities context = new DbMyPortfolioEntities();
        public ActionResult SkillList(int page = 1)
        {
            var values = context.Skill.ToList().ToPagedList(page,5);
            return View(values);
        }
        [HttpGet]
        public ActionResult CreateSkill()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSkill(Skill skill)
        {
            if (ModelState.IsValid)
            {
                context.Skill.Add(skill);
                context.SaveChanges();
                return RedirectToAction(nameof(SkillList));
            }
            return View(skill);
        }
        public ActionResult DeleteSkill(int id)
        {
            var value = context.Skill.Find(id);
            context.Skill.Remove(value);
            context.SaveChanges();
            return RedirectToAction(nameof(SkillList));
        }
        [HttpGet]
        public ActionResult UpdateSkill(int id)
        {
            var value = context.Skill.Find(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult UpdateSkill(Skill skill)
        {
            var value = context.Skill.Find(skill.SkillID);
            value.SkillName = skill.SkillName;
            value.Rate = skill.Rate;
            context.SaveChanges();
            return RedirectToAction(nameof(SkillList));
        }
    }
}

MyPortfolioProject/Views/Skill/CreateSkill.cshtml
@{
    ViewBag.Title = "CreateSkill";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Yeni Yetenek Ekleme Sayfası</h2>

<form method="post">
    <label>Yetenek Başlığı</label>
    <input type="text" name="SkillName" class="form-control" />
    @Html.ValidationMessage("SkillName", "", new { @class = "text-danger" })
    <br />
    <label>Yetenek Değeri</label>
    <input type="number" name="Rate" class="form-control" />
    @Html.ValidationMessage("Rate", "", new { @class = "text-danger" })
    <br />
    <button class="btn btn-outline-info">Yeteneği Ekle</button>
</form>

MyPortfolioProject/Views/Skill/SkillList.cshtml
@using PagedList
@using PagedList.Mvc

@model PagedList.IPagedList<MyPortfolioProject.Models.Skill>

@{
    ViewBag.Title = "SkillList";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Yetenek Listesi ve İşlemleri</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>Değer</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SkillID</td>
            <td>@item.SkillName</td>
            <td>@item.Rate</td>
            <td><a href="/Skill/DeleteSkill/@item.SkillID/" class="btn btn-outline-danger">Sil</a></td>
            <td><a href="/Skill/UpdateSkill/@item.SkillID/" class="btn btn-outline-success">Güncelle</a></td>
        </tr>
    }


</table>

@Html.PagedListPager(Model, page => Url.Action("SkillList", new { page }))
<style>
    .pagination {
        display: flex;
        list-style-type: none;
        padding: 0;
    }

        .pagination li {
            margin: 0 5px;
        }

            .pagination li a, .pagination li span {
                display: block;
                padding: 8px 16px;
                border: 1px solid #ddd;
                text-decoration: none;
                color: #333;
            }

                .pagination li a:hover {
                    background-color: #f2f2f2;
                    border-color: #333;
                }

            .pagination li.active span {
                background-color: #007bff;
                color: white;
                border-color: #007bff;
            }

            .pagination li.disabled span {
                color: #ccc;
            }

</style>
<a href="/Skill/CreateSkill/" class="btn btn-outline-info">Yetenek Ekle</a>

MyPortfolioProject/Views/Skill/UpdateSkill.cshtml
@model MyPortfolioProject.Models.Skill
@{
    ViewBag.Title = "UpdateSkill";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Yetenek Güncelleme Sayfası</h2>


@using (Html.BeginForm("UpdateSkill", "Skill", FormMethod.Post))
{
    @Html.HiddenFor(k => k.SkillID)
    <div class="form-group">
        <label>Ad</label>
        @Html.TextBoxFor(k => k.SkillName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Soyad</label>
        @Html.TextBoxFor(k => k.Rate, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn btn-outline-info">Güncelle</button>
    </div>
}